// Code generated by goctl. DO NOT EDIT.
package types

type MatchRequest struct {
	UserId  int64 `json:"userId"`
	Rank    int64 `json:"rank"`
	NeedNum int64 `json:"needNum"`
}

type MatchResponse struct {
	RoomId int64 `json:"roomId"`
}

type OcrRequest struct {
	File     string `json:"file"`
	Type     string `json:"type"`
	FileType int    `json:"fileType"`
}

type OcrResponse struct {
	Result interface{} `json:"result"`
}
